compile_pdf:
  image: aergus/latex
  script:
    - latexmk -pdf file.tex
  artifacts:
    paths:
      - file.pdf
  environment:
    name: ParamicsDiscovery.exe
    url: https://gitlab.com/joostlek/$CI_PROJECT_PATH/jobs/$CI_BUILD_ID/artifacts/file/file.pdf